### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by alrra** [webhintio/hint#1133]
- [ ] Normalize / Standardize error massages. (See: #1170)
- [x] Make event related changes (done in #1055)
- [x] Change `getRuleName` to `getRulePath` (See: #1134)
- [x] Extract connectors to packages (@sarvaje)
- [x] Webpack bundle, we will probably break packages for the `utils` part (@molant) --> Not bundling the main CLI but rather optimize the dependencies
- [x] Extract wizards to their own packages (See: #1132) (@molant)
- [x] Remove `plugins` [from config](https://github.com/sonarwhal/sonarwhal/blob/a929058af3b44eaf89627f361f3d5c9ef31ab22d/packages/sonarwhal/src/lib/types.ts#L64) (done in #1141).
- [x] Event to evalute JS (See : #497)
- [x] Move `cdp-async-html` to `utils-debugging-protocol` package (See #1184).
- [x] Other (?)

**Comment by molant** [comment]
* [ ] Extract connectors to packages
* [ ] Webpack bundle, we will probably break packages for the `utils` part

**Comment by molant** [comment]
* [ ] Extract wizards to their own pacakges (See: #1132)

**Comment by alrra** [comment]
- [ ] Change `getRuleName` to `getRulePath` (See: #1134)

**Comment by molant** [comment]
- [ ] Remove `plugins` [from config](https://github.com/sonarwhal/sonarwhal/blob/a929058af3b44eaf89627f361f3d5c9ef31ab22d/packages/sonarwhal/src/lib/types.ts#L64)

**Comment by molant** [comment]
- [ ] Event to evalute JS (See : #497)

**Comment by molant** [comment]
- [ ] Normalize / Standardize error massages. (See: #1170)

**Comment by molant** [comment]
- [ ] Move `cdp-async-html` to `utils-debugging-protocol` package
