### ISSUE TITLE
Update jsdom to new API

### ISSUE THREAD

**Issue by molant** [webhintio/hint#163]
[jsdom's new version](https://github.com/tmpvar/jsdom) has a new and shiny API :tada:

PR #144 updates to v10 but it uses [the old API](https://github.com/tmpvar/jsdom/blob/master/lib/old-api.md) so #161 gets unblocked once it is merged.

We should update to the new way of doings things asap (although there seems to be a few features that are not yet supported.

Sub-tasks:

* [x] Websites with relative links will not load correctly #96 
* [x] Create infrastructure to inject JS #129 
* [x] Add  [`canvas`](https://www.npmjs.com/package/canvas) or [`canvas-prebuilt`](https://www.npmjs.com/package/canvas-prebuilt) as a peer dependency to download the images #241

**Comment by molant** [comment]
We still need `resourceLoader` to migrate to the new API. We should evaluate adding that feature so we can migrate to the new API. The new API seems to be more reliable as we can see in #521 and #589 so this might be worth trying to improve our success rate in the online scanner.

**Comment by alrra** [comment]
> resourceLoader

New resource loader API is now available in `v12`, see: https://github.com/jsdom/jsdom/blob/master/Changelog.md#1200 🎉

Great work @sarvaje!
