### ISSUE TITLE
Browser extension UI design improvements [8]

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1778]
- [x] Improve design of landing "page" with configuration options [3]
- [x] Adjust "analyzing" page to match updated designs
- [x] Improve design of scan results "page"
