### ISSUE TITLE
[planning] Retrospective and planning for 1905-2 (05/10/2019)

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2403]
**Time**: 05/10/2019 09:00 PST
**Meeting link (participants)**: https://zoom.us/j/211950755
**YouTube streaming/recording**: TBD
**Google docs for notes**: [webhint planning meeting 2019-05-10](https://docs.google.com/document/d/1q5AKdOWMs-WzSGlNJL0uDCvc6aBo4ymQLNsP6U4L4Mk/edit)

# Extension bundles

* Firefox: [webhint-1.0-an+fx.xpi.zip](https://github.com/webhintio/hint/files/3159562/webhint-1.0-an%2Bfx.xpi.zip)
  * Remove `.zip` from the file name and add to Firefox via `about:addons`
* Chrome: [webhint-1.0.0.zip](https://github.com/webhintio/hint/files/3159630/webhint-1.0.0.zip)
  * Unzip, go to `chrome://extensions` (or `edge://extensions` if you are running Edge), enable developer mode if you haven't already, click on "load unpacked" and select the unzipped folder 

# Agenda

## Action items from previous meeting

**Connector-chromium**

* [ ] There's puppeteer for Firefox currently on the works, need to document the methods we are using to see if it will work once it's out of beta (@molant)
* [x] Rename `connector-chromium` to `connector-puppeteer` (@molant)

**Extension**

* [x] Share [signed beta bundle](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/web-ext_command_reference#web-ext_sign) to start getting feedback (see #1640)
* [x] Link to the elements panel with an offset to point to the right place and link to the network panel (latter requires a new API). @digitarald to update the bugs in Mozilla's side. → **https://bugzilla.mozilla.org/show_bug.cgi?id=1548467**
* [x] Get a designed integrated. @violasong working on the design and will be sharing more mockups. Once #1670 (and maybe #1669) are done @molant will create a new issue to ping Harald so Mozilla can start implementing it.
  * Issue #2424 created
* [x] @antross to review [the guidance](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy/Reviews#Data_Disclosure_Collection_and_Management) to see if it applies to our case (we bundle AppInsights directly and no code is downloaded during execution). --> Should be fine although we are using a beta version. Thinking about doing rest calls directly
* [ ] We will also do some a11y checks on our side.
  * @molant to ping Amanda to see how they are doing it and see how we can automate most of it on webhint (#1678)
* [ ] Surveys: There's infrastructure in Mozilla's side to get surveys to targeted users. @digitarald, @brendyna and @paulgildea to partner to craft the right questions.

## New Items

* [x] What we've finished (or almost finished for the sprint)
  * Problems?
* [x] Status of the browser extension
  * [x] [Can there be multiple publishers/admins for one extension](https://github.com/webhintio/hint/issues/1641#issuecomment-491313038)?
* [x] What tasks are moving to the next sprint
* [x] Where to track feedback from the extension (For now is issue #1640, do we need something else?)
* [x] Backlog for next sprint
* [x] MDN:  We've created an utility to query the data. Maybe have it as a separate package?

# Action items

* [x] @antross to comment on the [navigation API for the Network Panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1548467)
* [x] @molant to publish the extension unlisted in different stores (#1641)
* [ ] @ststimac and @violasong to sync about design and see what can be reconciled between both designs and what can't so implementing themes is easier (#2424)
* [x] @digitarald reach out to engineers when extension is in the store
* [ ] @brendyna, @digitarald, @paulgildea to start crafting a survey for users of the extension
* [ ] @antross to open an issue on [browser-compat-data](https://github.com/mdn/browser-compat-data) about the util we have to query their data
* [ ] @antross to disable manifest property that shows warning on Firefox installation (tracked in #1640 Known issues)
* [ ] @molant to list used `puppeteer` API when the connector is finished

## Links and others

* https://github.com/dadaa/compat-icon/ 

![compat-addon](https://user-images.githubusercontent.com/785009/58272148-77f7d900-7d53-11e9-9698-b520ba0a1f7a.gif)

**Comment by molant** [comment]
Feel free to suggest other items!

**Comment by molant** [comment]
# Action items

* [ ] @antross to comment on the [navigation API for the Network Panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1548467)
* [ ] @molant to publish the extension unlisted in different stores (#1641)
* [ ] @ststimac and @violasong to sync about design and see what can be reconciled between both designs and what can't so implementing themes is easier (#2424)
* [ ] @digitarald reach out to engineers when extension is in the store
* [ ] @brendyna, @digitarald, @paulgildea to start crafting a survey for users of the extension
* [ ] @antross to open an issue on [browser-compat-data](https://github.com/mdn/browser-compat-data) about the util we have to query their data
* [ ] @antross to disable manifest property that shows warning on Firefox installation (tracked in #1640 Known issues)

**Comment by antross** [comment]
![compat-addon](https://user-images.githubusercontent.com/785009/58272148-77f7d900-7d53-11e9-9698-b520ba0a1f7a.gif)
