### ISSUE TITLE
Browser extension small issues

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2408]
This is an epic to keep track of all the small things we want to improve in the browser extension.
The idea is to make the reporting faster. Individual issues will be created when they are being addressed.

* [ ] Fix hit area for toggle
* [ ] Fix "Restore defaults" position inside button
* [ ] Focus rect in details/summary error page
* [ ] Toggle types needs to be migrated
* [ ] Make analyzing overflow be responsive with narrow width
* [ ] Move up pending colors (like shadows) --> Do it when we want to tweak it for another theme
* [ ] Use grid in `label.css` to avoid descendant selector
* [ ] Remove `label-text` control once the label control uses grid
* [ ] Check if `!important;` usages are needed in progress bar control

**Comment by molant** [comment]
Closing in favor of #1640 that also has the bundles
