### ISSUE TITLE
[planning] Retrospective and planning for 1906-1 (05/24/2019)

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2498]
**Time**: 05/24/2019 09:00 PST
**Meeting link (participants)**: https://zoom.us/j/211950755
**YouTube streaming/recording**: https://youtu.be/5PItENe8dgI
**Google docs for notes**: [webhint planning live notes](https://docs.google.com/document/d/1q5AKdOWMs-WzSGlNJL0uDCvc6aBo4ymQLNsP6U4L4Mk/edit)

# Extension store links

* [**Firefox**](https://addons.mozilla.org/en-US/firefox/addon/webhint/)
* [**Chromium**](https://chrome.google.com/webstore/detail/webhint/gccemnpihkbgkdmoogenkbkckppadcag)

# Agenda

## New Items
* How to change extension tab icon or icon color with theme and active context?
* Infra is ready for Firefox to start implementing design. Schedule sync to go through it?
* Interest in discussing the devtools network API with the Edge devtools team?

## Done
* New release of `hint` and related packages published with connector-puppeteer
* Extension v0.0.2 has been published with improved error handling and bug fixes
* 2 micro services migrated to serverless and in PR review
* Support for authentication via connector-puppeteer

## In Progress
* Refactor hint-compat-api to use new compat util wrapper around MDN data
* PR open to browserslist to remove Android WebView 4.4.3-4.4.4 from defaults

## Action items from previous meeting

* [x] @antross to comment on the [navigation API for the Network Panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1548467)
* [x] @molant to publish the extension unlisted in different stores (#1641)
* [x] @molant to list used `puppeteer` API when the connector is finished. Updated https://github.com/webhintio/hint/issues/377 with all the information
* [ ] @ststimac and @violasong to sync about design and see what can be reconciled between both designs and what can't so implementing themes is easier (#2424)
* [ ] @brendyna, @digitarald, @paulgildea to start crafting a survey for users of the extension

* [ ] @antross to disable manifest property that shows warning on Firefox installation (tracked in #1640 Known issues)
* [ ] We will also do some a11y checks on our side.
  * @molant to ping Amanda to see how they are doing it and see how we can automate most of it on webhint (#1678)
* [ ] Surveys: There's infrastructure in Mozilla's side to get surveys to targeted users. @digitarald, @brendyna and @paulgildea to partner to craft the right questions.

## New Items

* [ ] @digitarald, @paulgildea to draft blog post for preview versions of the extension

# Action items

* [ ]
