### ISSUE TITLE
Add rule to check the usage of `<meta>` charset

### ISSUE THREAD

**Issue by alrra** [webhintio/hint#81]
- [x] Check if the if the meta tag is not included completely within the first 1024 bytes of the document - done by the [markdown validator](https://validator.w3.org/) (see: #28)

- [x] Check if meta tag is not specified as early as possible (before any content that could be controlled by an attacker, such as a `<title>` element) so to avoid a [potential encoding-related security issue](https://code.google.com/archive/p/doctype-mirror/wikis/ArticleUtf7.wiki) in Internet Explorer (Note: this was only an issue with IE6?).

- [x] Check if non-[`utf-8` encodings are used](https://blog.whatwg.org/the-road-to-html-5-character-encoding)

- [x] Check if things like `utf8` are used (even though this is valid nowadays as the [specifications](https://encoding.spec.whatwg.org/#names-and-labels) and [browsers](https://twitter.com/jacobrossi/status/591435377291866112) alias `utf8` to `utf-8`, [that wasn't the case in the past](https://twitter.com/sil/status/591361598599667714)).

- [x] Check if the [short version is used](https://blog.whatwg.org/meta-charset) (i.e.: `<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">` => `<meta charset="utf-8">` ).

- [x] Other?
